[package]
name = "msi_control"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ksni = "0.2"
png = "0.17"
dbus = "0.9"